export interface User {
  id: string;
  first: string;
  last: string;
  role: "admin" | "manager";
  region: string;
  funnel: string;
}

export const INITIAL_USERS: User[] = [
  { id: "admin", first: "Gabriel", last: "Carriere", role: "admin", region: "Global", funnel: "All" },
  { id: "manager", first: "Sales", last: "Manager", role: "manager", region: "Global", funnel: "All" },
  // Benelux Inbound
  { id: "daniel.aarts", first: "Daniel", last: "Aarts", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "chloe.verstraeten", first: "Chloe", last: "Verstraeten", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "laura.wagemans", first: "Laura", last: "Wagemans", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "riad.elakari", first: "Riad", last: "Elakari", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "sofyen.zahaf", first: "Sofyen", last: "Zahaf", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "jozef.berhitu", first: "Jozef", last: "Berhitu", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "antoine.andries", first: "Antoine", last: "Andries", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "tom.van hooland", first: "Tom", last: "Van Hooland", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "rick.van doorn", first: "Rick", last: "Van Doorn", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "jerome.bernaerd", first: "Jerome", last: "Bernaerd", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "lukas.vandenbogaerde", first: "Lukas", last: "Vandenbogaerde", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "thom.de koning", first: "Thom", last: "De Koning", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "jonas.festre", first: "Jonas", last: "Festre", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "laurens.sierens", first: "Laurens", last: "Sierens", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "piet.verlinde", first: "Piet", last: "Verlinde", role: "admin", region: "Benelux", funnel: "Inbound" },
  { id: "jasper.luijkx", first: "Jasper", last: "Luijkx", role: "admin", region: "Benelux", funnel: "Inbound" },
  // Benelux Outbound
  { id: "milan.schuermans", first: "Milan", last: "Schuermans", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "evi.kelepouris", first: "Evi", last: "Kelepouris", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "ouassim.yaakoubi", first: "Ouassim", last: "Yaakoubi", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "tine.matthee", first: "Tine", last: "Matthee", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "juliet.doeze", first: "Juliet", last: "Doeze", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "rachelle.gihousse", first: "Rachelle", last: "Gihousse", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "michelle.brouns", first: "Michelle", last: "Brouns", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "tristan.tak", first: "Tristan", last: "Tak", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "estelle.fenichiu", first: "Estelle", last: "Fenichiu", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "jonathan.alcoba", first: "Jonathan", last: "Alcoba", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "lamiae.souirat", first: "Lamiae", last: "Souirat", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "crystal.beerman", first: "Crystal", last: "Beerman", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "enzo.beers", first: "Enzo", last: "Beers", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "gijs.jacobs", first: "Gijs", last: "Jacobs", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "karst.karsten", first: "Karst", last: "Karsten", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "luk.detroyer", first: "Luk", last: "DeTroyer", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "tyrel.meije", first: "Tyrel", last: "Meije", role: "admin", region: "Benelux", funnel: "Outbound" },
  { id: "amy.walschots", first: "Amy", last: "Walschots", role: "admin", region: "Benelux", funnel: "Outbound" },
  // France Inbound
  { id: "alhadji.sylla", first: "Alhadji", last: "Sylla", role: "admin", region: "France", funnel: "Inbound" },
  { id: "amine.chader", first: "Amine", last: "Chader", role: "admin", region: "France", funnel: "Inbound" },
  { id: "michael.rahmani", first: "Michael", last: "Rahmani", role: "admin", region: "France", funnel: "Inbound" },
  { id: "julien.koussou", first: "Julien", last: "Koussou", role: "admin", region: "France", funnel: "Inbound" },
  { id: "pierre-ilies.bauer", first: "Pierre-Ilies", last: "Bauer", role: "admin", region: "France", funnel: "Inbound" },
  { id: "wardley.devarieux", first: "Wardley", last: "Devarieux", role: "admin", region: "France", funnel: "Inbound" },
  { id: "youssef.feki", first: "Youssef", last: "Feki", role: "admin", region: "France", funnel: "Inbound" },
  { id: "antoine.lebeau", first: "Antoine", last: "Lebeau", role: "admin", region: "France", funnel: "Inbound" },
  { id: "david.raimbault", first: "David", last: "Raimbault", role: "admin", region: "France", funnel: "Inbound" },
  { id: "mathieu.guedon", first: "Mathieu", last: "Guedon", role: "admin", region: "France", funnel: "Inbound" },
  { id: "axel.krieger", first: "Axel", last: "Krieger", role: "admin", region: "France", funnel: "Inbound" },
  { id: "judicael.mbotto", first: "Judicael", last: "Mbotto", role: "admin", region: "France", funnel: "Inbound" },
  { id: "sirine.marnaoui", first: "Sirine", last: "Marnaoui", role: "admin", region: "France", funnel: "Inbound" },
  { id: "selim.ozdemir-deleaunait", first: "Selim", last: "Ozdemir-Deleaunait", role: "admin", region: "France", funnel: "Inbound" },
  // France Outbound
  { id: "cheula.taylor", first: "Cheula", last: "Taylor", role: "admin", region: "France", funnel: "Outbound" },
  { id: "pauline.millochau", first: "Pauline", last: "Millochau", role: "admin", region: "France", funnel: "Outbound" },
  { id: "quentin.lemaire", first: "Quentin", last: "Lemaire", role: "admin", region: "France", funnel: "Outbound" },
  { id: "enzo.defrancesco", first: "Enzo", last: "DeFrancesco", role: "admin", region: "France", funnel: "Outbound" },
  { id: "valentin.lallier", first: "Valentin", last: "Lallier", role: "admin", region: "France", funnel: "Outbound" },
  { id: "bruno.labelle", first: "Bruno", last: "Labelle", role: "admin", region: "France", funnel: "Outbound" },
  { id: "roberto.gomez", first: "Roberto", last: "Gomez", role: "admin", region: "France", funnel: "Outbound" },
  { id: "axelle.laine", first: "Axelle", last: "Laine", role: "admin", region: "France", funnel: "Outbound" },
  { id: "romain.renard", first: "Romain", last: "Renard", role: "admin", region: "France", funnel: "Outbound" },
  { id: "aurélien.vol", first: "Aurélien", last: "Vol", role: "admin", region: "France", funnel: "Outbound" },
  { id: "marius.flour", first: "Marius", last: "Flour", role: "admin", region: "France", funnel: "Outbound" },
  { id: "jessica.michaut", first: "Jessica", last: "Michaut", role: "admin", region: "France", funnel: "Outbound" },
  { id: "damien.laumonerie", first: "Damien", last: "Laumonerie", role: "admin", region: "France", funnel: "Outbound" },
  { id: "samara.senoville", first: "Samara", last: "Senoville", role: "admin", region: "France", funnel: "Outbound" },
  { id: "julien.pierrel", first: "Julien", last: "Pierrel", role: "admin", region: "France", funnel: "Outbound" },
  { id: "raphael.rocca", first: "Raphael", last: "Rocca", role: "admin", region: "France", funnel: "Outbound" },
  { id: "alexis.dufour", first: "Alexis", last: "Dufour", role: "admin", region: "France", funnel: "Outbound" },
  { id: "agathe.moscovici", first: "Agathe", last: "Moscovici", role: "admin", region: "France", funnel: "Outbound" },
  { id: "aurelien.sancho", first: "Aurelien", last: "Sancho", role: "admin", region: "France", funnel: "Outbound" },
  { id: "antoine.dupupet", first: "Antoine", last: "Dupupet", role: "admin", region: "France", funnel: "Outbound" },
  { id: "menel.amraoui", first: "Menel", last: "Amraoui", role: "admin", region: "France", funnel: "Outbound" },
  { id: "valerian.girardin", first: "Valerian", last: "Girardin", role: "admin", region: "France", funnel: "Outbound" },
  { id: "raphael.demer", first: "Raphael", last: "Demer", role: "admin", region: "France", funnel: "Outbound" },
  { id: "kevin.lo", first: "Kevin", last: "Lo", role: "admin", region: "France", funnel: "Outbound" },
];
